# Generated by Django 2.2.3 on 2019-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('hsn', models.CharField(max_length=30)),
                ('pack', models.CharField(max_length=15)),
                ('batch', models.CharField(max_length=20)),
                ('exp_data', models.DateTimeField()),
                ('qty', models.IntegerField()),
                ('free', models.CharField(max_length=20)),
                ('mrp', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
